-- ============================================================
-- BIOSYNC COMPREHENSIVE SCHEMA - Missing Tables
-- This file contains SQL definitions for tables referenced
-- in the codebase but not yet defined in the schema files.
-- Run this in Supabase SQL Editor after the base schemas.
-- ============================================================

-- ============================================================
-- 0. AI-GENERATED MISSIONS (weekly + daily, generated by DeepSeek AI)
-- ============================================================

-- Weekly missions: AI generates 5 personalized missions every Monday
-- based on user level, league tier, and recent activity history.
CREATE TABLE IF NOT EXISTS weekly_missions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    title_tr VARCHAR(255),
    description TEXT,
    description_tr TEXT,
    category VARCHAR(50) NOT NULL DEFAULT 'workout', -- workout, nutrition, health, social, streak
    target_value INTEGER NOT NULL DEFAULT 1,
    current_progress INTEGER NOT NULL DEFAULT 0,
    xp_reward INTEGER NOT NULL DEFAULT 100,
    point_reward INTEGER NOT NULL DEFAULT 50,
    is_completed BOOLEAN DEFAULT false,
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Daily missions: AI generates 3 quick missions each day
CREATE TABLE IF NOT EXISTS daily_missions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    title_tr VARCHAR(255),
    description TEXT,
    description_tr TEXT,
    category VARCHAR(50) NOT NULL DEFAULT 'workout', -- workout, nutrition, health
    target_value INTEGER NOT NULL DEFAULT 1,
    current_progress INTEGER NOT NULL DEFAULT 0,
    xp_reward INTEGER NOT NULL DEFAULT 20,
    point_reward INTEGER NOT NULL DEFAULT 10,
    is_completed BOOLEAN DEFAULT false,
    mission_date DATE NOT NULL DEFAULT CURRENT_DATE,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE weekly_missions ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_missions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own weekly_missions" ON weekly_missions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own daily_missions" ON daily_missions FOR ALL USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_weekly_missions_user_week ON weekly_missions(user_id, week_start, week_end);
CREATE INDEX IF NOT EXISTS idx_daily_missions_user_date ON daily_missions(user_id, mission_date);

-- ============================================================
-- 1. CORE DATA TABLES (used by supabase.ts)
-- ============================================================

CREATE TABLE IF NOT EXISTS exercises (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    name_tr VARCHAR(255),
    description TEXT,
    description_tr TEXT,
    muscle_group VARCHAR(100),
    secondary_muscles TEXT[],
    equipment VARCHAR(100),
    difficulty VARCHAR(20) DEFAULT 'intermediate', -- beginner, intermediate, advanced
    instructions TEXT[],
    tips TEXT[],
    calories_per_rep NUMERIC(5,2) DEFAULT 0,
    image_url TEXT,
    video_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS food_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    name_tr VARCHAR(255),
    category VARCHAR(100),
    calories NUMERIC(8,2) DEFAULT 0,
    protein NUMERIC(8,2) DEFAULT 0,
    carbs NUMERIC(8,2) DEFAULT 0,
    fat NUMERIC(8,2) DEFAULT 0,
    fiber NUMERIC(8,2) DEFAULT 0,
    serving_size VARCHAR(100),
    serving_unit VARCHAR(50),
    barcode VARCHAR(100),
    image_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS food_scans (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    food_item_id UUID REFERENCES food_items(id),
    scan_type VARCHAR(50) DEFAULT 'photo', -- photo, barcode
    image_url TEXT,
    ai_result JSONB,
    calories NUMERIC(8,2),
    protein NUMERIC(8,2),
    carbs NUMERIC(8,2),
    fat NUMERIC(8,2),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS health_records (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    record_type VARCHAR(50) NOT NULL, -- steps, heart_rate, sleep, blood_pressure
    value NUMERIC(10,2),
    unit VARCHAR(30),
    metadata JSONB,
    recorded_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 2. WATER TRACKING (to enable Supabase sync)
-- ============================================================

CREATE TABLE IF NOT EXISTS water_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    amount_ml INTEGER NOT NULL DEFAULT 0,
    goal_ml INTEGER NOT NULL DEFAULT 2500,
    drink_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, date)
);

-- ============================================================
-- 3. AI & NUTRITION PLANS
-- ============================================================

CREATE TABLE IF NOT EXISTS meal_plans (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    name VARCHAR(255),
    description TEXT,
    goal VARCHAR(100),
    daily_calories INTEGER,
    daily_protein NUMERIC(8,2),
    daily_carbs NUMERIC(8,2),
    daily_fat NUMERIC(8,2),
    meals JSONB, -- array of meal objects
    is_active BOOLEAN DEFAULT true,
    created_by VARCHAR(50) DEFAULT 'ai', -- ai, professional, user
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS nutrition_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    food_item_id UUID REFERENCES food_items(id),
    meal_type VARCHAR(50), -- breakfast, lunch, dinner, snack
    food_name VARCHAR(255),
    calories NUMERIC(8,2),
    protein NUMERIC(8,2),
    carbs NUMERIC(8,2),
    fat NUMERIC(8,2),
    serving_size NUMERIC(8,2),
    serving_unit VARCHAR(50),
    logged_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS nutrition_plans (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    professional_id UUID REFERENCES profiles(id),
    name VARCHAR(255),
    description TEXT,
    daily_calories INTEGER,
    meals JSONB,
    is_active BOOLEAN DEFAULT true,
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS workout_plans (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    name VARCHAR(255),
    description TEXT,
    goal VARCHAR(100),
    difficulty VARCHAR(20),
    days_per_week INTEGER DEFAULT 4,
    exercises JSONB, -- array of exercise plan objects
    is_active BOOLEAN DEFAULT true,
    created_by VARCHAR(50) DEFAULT 'ai',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS workout_sessions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    workout_id UUID REFERENCES workouts(id),
    workout_plan_id UUID REFERENCES workout_plans(id),
    duration_seconds INTEGER,
    calories_burned NUMERIC(8,2),
    heart_rate_avg INTEGER,
    exercises_completed JSONB,
    notes TEXT,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 4. AI ANALYSIS & PREFERENCES
-- ============================================================

CREATE TABLE IF NOT EXISTS ai_analyses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    analysis_type VARCHAR(50) NOT NULL, -- posture, food, body_composition
    input_data JSONB,
    result JSONB,
    confidence_score NUMERIC(5,2),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_preferences (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    preference_type VARCHAR(50) NOT NULL,
    value JSONB,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, preference_type)
);

CREATE TABLE IF NOT EXISTS user_goals (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    goal_type VARCHAR(50) NOT NULL, -- weight, muscle, endurance, flexibility
    target_value NUMERIC(10,2),
    current_value NUMERIC(10,2),
    unit VARCHAR(30),
    deadline DATE,
    is_achieved BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS food_preferences (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    dietary_restrictions TEXT[], -- vegan, vegetarian, gluten-free, etc.
    allergies TEXT[],
    favorite_foods TEXT[],
    disliked_foods TEXT[],
    cuisine_preferences TEXT[],
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id)
);

CREATE TABLE IF NOT EXISTS progress_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    log_type VARCHAR(50) NOT NULL, -- weight, body_fat, measurement
    value NUMERIC(10,2),
    unit VARCHAR(30),
    notes TEXT,
    photo_url TEXT,
    logged_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sleep_data (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    duration_hours NUMERIC(4,2),
    quality_score INTEGER, -- 1-100
    deep_sleep_minutes INTEGER,
    rem_sleep_minutes INTEGER,
    light_sleep_minutes INTEGER,
    awake_minutes INTEGER,
    bedtime TIME,
    wake_time TIME,
    source VARCHAR(50), -- manual, apple_health, google_fit
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, date)
);

CREATE TABLE IF NOT EXISTS stress_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    stress_level INTEGER NOT NULL, -- 1-10
    notes TEXT,
    triggers TEXT[],
    coping_methods TEXT[],
    logged_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_feedback (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    feedback_type VARCHAR(50), -- bug, feature, general
    subject VARCHAR(255),
    message TEXT,
    rating INTEGER, -- 1-5
    status VARCHAR(30) DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 5. COMMUNITY & SOCIAL
-- ============================================================

CREATE TABLE IF NOT EXISTS forum_categories (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    name_tr VARCHAR(255),
    description TEXT,
    icon VARCHAR(50),
    color VARCHAR(20),
    sort_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS forum_topics (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    category_id UUID NOT NULL REFERENCES forum_categories(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    title VARCHAR(500) NOT NULL,
    content TEXT,
    is_pinned BOOLEAN DEFAULT false,
    is_locked BOOLEAN DEFAULT false,
    view_count INTEGER DEFAULT 0,
    like_count INTEGER DEFAULT 0,
    reply_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS forum_posts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    topic_id UUID NOT NULL REFERENCES forum_topics(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    parent_post_id UUID REFERENCES forum_posts(id),
    like_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS topic_likes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    topic_id UUID NOT NULL REFERENCES forum_topics(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(topic_id, user_id)
);

CREATE TABLE IF NOT EXISTS post_likes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    post_id UUID NOT NULL REFERENCES forum_posts(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(post_id, user_id)
);

CREATE TABLE IF NOT EXISTS forum_polls (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    topic_id UUID NOT NULL REFERENCES forum_topics(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    options JSONB NOT NULL,
    ends_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS poll_votes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    poll_id UUID NOT NULL REFERENCES forum_polls(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    option_index INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(poll_id, user_id)
);

CREATE TABLE IF NOT EXISTS social_posts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    content TEXT,
    media_urls TEXT[],
    post_type VARCHAR(50) DEFAULT 'general', -- general, workout, achievement, progress
    like_count INTEGER DEFAULT 0,
    comment_count INTEGER DEFAULT 0,
    is_public BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS post_comments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    post_id UUID NOT NULL REFERENCES social_posts(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    parent_comment_id UUID REFERENCES post_comments(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS follows (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    follower_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    following_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(follower_id, following_id)
);

CREATE TABLE IF NOT EXISTS challenges (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    creator_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    challenge_type VARCHAR(50), -- workout, steps, water, nutrition
    target_value NUMERIC(10,2),
    unit VARCHAR(30),
    start_date DATE,
    end_date DATE,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS challenge_participants (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    challenge_id UUID NOT NULL REFERENCES challenges(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    current_progress NUMERIC(10,2) DEFAULT 0,
    is_completed BOOLEAN DEFAULT false,
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(challenge_id, user_id)
);

-- ============================================================
-- 6. NOTIFICATIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS notifications (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    body TEXT,
    type VARCHAR(50), -- workout, nutrition, social, system, achievement
    data JSONB,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_push_tokens (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    token TEXT NOT NULL,
    platform VARCHAR(20), -- ios, android, web
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, token)
);

CREATE TABLE IF NOT EXISTS notification_preferences (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    notification_type VARCHAR(50) NOT NULL,
    enabled BOOLEAN DEFAULT true,
    UNIQUE(user_id, notification_type)
);

CREATE TABLE IF NOT EXISTS scheduled_notifications (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    title VARCHAR(255),
    body TEXT,
    scheduled_for TIMESTAMPTZ NOT NULL,
    sent BOOLEAN DEFAULT false,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 7. PAYMENTS & SUBSCRIPTIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS subscription_plans (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    name_tr VARCHAR(255),
    description TEXT,
    price NUMERIC(10,2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'USD',
    interval VARCHAR(20) DEFAULT 'monthly', -- monthly, yearly
    features JSONB,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_subscriptions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    plan_id UUID NOT NULL REFERENCES subscription_plans(id),
    status VARCHAR(30) DEFAULT 'active', -- active, cancelled, expired
    start_date TIMESTAMPTZ DEFAULT NOW(),
    end_date TIMESTAMPTZ,
    store_transaction_id VARCHAR(255),
    platform VARCHAR(20), -- ios, android
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payment_methods (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    type VARCHAR(30), -- card, apple_pay, google_pay
    last_four VARCHAR(4),
    brand VARCHAR(30),
    is_default BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS invoices (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    subscription_id UUID REFERENCES user_subscriptions(id),
    amount NUMERIC(10,2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'USD',
    status VARCHAR(30) DEFAULT 'paid',
    invoice_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payment_history (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    amount NUMERIC(10,2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'USD',
    payment_type VARCHAR(30), -- subscription, one_time
    status VARCHAR(30) DEFAULT 'completed',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 8. PROGRESS REPORTS
-- ============================================================

CREATE TABLE IF NOT EXISTS progress_reports (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    report_type VARCHAR(50), -- weekly, monthly, custom
    period_start DATE,
    period_end DATE,
    data JSONB,
    summary TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS shared_reports (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    report_id UUID NOT NULL REFERENCES progress_reports(id) ON DELETE CASCADE,
    shared_with UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    shared_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(report_id, shared_with)
);

CREATE TABLE IF NOT EXISTS goals (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    goal_type VARCHAR(50),
    target_value NUMERIC(10,2),
    current_value NUMERIC(10,2) DEFAULT 0,
    unit VARCHAR(30),
    deadline DATE,
    status VARCHAR(30) DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 9. WEARABLE DEVICES & HEALTH
-- ============================================================

CREATE TABLE IF NOT EXISTS wearable_devices (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    device_type VARCHAR(50), -- apple_watch, fitbit, garmin, samsung
    device_name VARCHAR(255),
    is_connected BOOLEAN DEFAULT true,
    last_sync_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS health_data (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    data_type VARCHAR(50) NOT NULL, -- steps, heart_rate, blood_oxygen, etc.
    value NUMERIC(10,2),
    unit VARCHAR(30),
    source VARCHAR(50), -- apple_health, google_fit, manual
    recorded_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS health_goals (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    goal_type VARCHAR(50) NOT NULL,
    target_value NUMERIC(10,2),
    current_value NUMERIC(10,2) DEFAULT 0,
    unit VARCHAR(30),
    is_achieved BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, goal_type)
);

-- ============================================================
-- 10. VIDEO CONTENT
-- ============================================================

CREATE TABLE IF NOT EXISTS videos (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    creator_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    title VARCHAR(500) NOT NULL,
    description TEXT,
    video_url TEXT NOT NULL,
    thumbnail_url TEXT,
    category VARCHAR(100),
    duration_seconds INTEGER,
    view_count INTEGER DEFAULT 0,
    like_count INTEGER DEFAULT 0,
    is_premium BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS video_progress (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    video_id UUID NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    progress_seconds INTEGER DEFAULT 0,
    is_completed BOOLEAN DEFAULT false,
    last_watched_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, video_id)
);

CREATE TABLE IF NOT EXISTS video_likes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    video_id UUID NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(video_id, user_id)
);

CREATE TABLE IF NOT EXISTS video_comments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    video_id UUID NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    parent_comment_id UUID REFERENCES video_comments(id),
    like_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS comment_likes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    comment_id UUID NOT NULL,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(comment_id, user_id)
);

CREATE TABLE IF NOT EXISTS video_playlists (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    is_public BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS playlist_videos (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    playlist_id UUID NOT NULL REFERENCES video_playlists(id) ON DELETE CASCADE,
    video_id UUID NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    sort_order INTEGER DEFAULT 0,
    added_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(playlist_id, video_id)
);

-- ============================================================
-- 11. ROW LEVEL SECURITY for all new tables
-- ============================================================

ALTER TABLE exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE food_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE food_scans ENABLE ROW LEVEL SECURITY;
ALTER TABLE health_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE water_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE meal_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE nutrition_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE nutrition_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE workout_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE workout_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_analyses ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE food_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE progress_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE sleep_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE stress_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE topic_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_polls ENABLE ROW LEVEL SECURITY;
ALTER TABLE poll_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE social_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE challenge_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_push_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE scheduled_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE progress_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE shared_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE wearable_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE health_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE health_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE comment_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_playlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE playlist_videos ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 12. RLS POLICIES
-- ============================================================

-- Public read for reference tables
CREATE POLICY "Anyone can read exercises" ON exercises FOR SELECT USING (true);
CREATE POLICY "Anyone can read food_items" ON food_items FOR SELECT USING (true);
CREATE POLICY "Anyone can read forum_categories" ON forum_categories FOR SELECT USING (true);
CREATE POLICY "Anyone can read subscription_plans" ON subscription_plans FOR SELECT USING (true);
CREATE POLICY "Anyone can read videos" ON videos FOR SELECT USING (is_active = true);

-- User-specific data policies
CREATE POLICY "Users manage own food_scans" ON food_scans FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own health_records" ON health_records FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own water_logs" ON water_logs FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own meal_plans" ON meal_plans FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own nutrition_logs" ON nutrition_logs FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own nutrition_plans" ON nutrition_plans FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own workout_plans" ON workout_plans FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own workout_sessions" ON workout_sessions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own ai_analyses" ON ai_analyses FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own preferences" ON user_preferences FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own goals_table" ON user_goals FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own food_prefs" ON food_preferences FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own progress_logs" ON progress_logs FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own sleep_data" ON sleep_data FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own stress_logs" ON stress_logs FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own feedback" ON user_feedback FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own notifications" ON notifications FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own push_tokens" ON user_push_tokens FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own notif_prefs" ON notification_preferences FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own scheduled_notifs" ON scheduled_notifications FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own subscriptions" ON user_subscriptions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own payment_methods" ON payment_methods FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own invoices" ON invoices FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own payment_history" ON payment_history FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own reports" ON progress_reports FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own shared_reports" ON shared_reports FOR ALL USING (auth.uid() = shared_with);
CREATE POLICY "Users manage own goals_gen" ON goals FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own wearables" ON wearable_devices FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own health_data" ON health_data FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own health_goals" ON health_goals FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own video_progress" ON video_progress FOR ALL USING (auth.uid() = user_id);

-- Social content policies
CREATE POLICY "Anyone read public forum_topics" ON forum_topics FOR SELECT USING (true);
CREATE POLICY "Users create forum_topics" ON forum_topics FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own forum_topics" ON forum_topics FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Anyone read forum_posts" ON forum_posts FOR SELECT USING (true);
CREATE POLICY "Users create forum_posts" ON forum_posts FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users manage own topic_likes" ON topic_likes FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own post_likes" ON post_likes FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Anyone read forum_polls" ON forum_polls FOR SELECT USING (true);
CREATE POLICY "Users manage own poll_votes" ON poll_votes FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Anyone read public social_posts" ON social_posts FOR SELECT USING (is_public = true);
CREATE POLICY "Users manage own social_posts" ON social_posts FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Anyone read post_comments" ON post_comments FOR SELECT USING (true);
CREATE POLICY "Users create post_comments" ON post_comments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users manage own follows" ON follows FOR ALL USING (auth.uid() = follower_id);
CREATE POLICY "Users manage own challenges" ON challenges FOR ALL USING (auth.uid() = creator_id);
CREATE POLICY "Anyone read challenges" ON challenges FOR SELECT USING (is_active = true);
CREATE POLICY "Users manage own challenge_parts" ON challenge_participants FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own video_likes" ON video_likes FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Anyone read video_comments" ON video_comments FOR SELECT USING (true);
CREATE POLICY "Users create video_comments" ON video_comments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users manage own comment_likes" ON comment_likes FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own playlists" ON video_playlists FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users manage own playlist_videos" ON playlist_videos FOR ALL USING (
    EXISTS (SELECT 1 FROM video_playlists WHERE id = playlist_videos.playlist_id AND user_id = auth.uid())
);

-- ============================================================
-- 13. INDEXES for performance
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_food_scans_user ON food_scans(user_id);
CREATE INDEX IF NOT EXISTS idx_health_records_user ON health_records(user_id, record_type);
CREATE INDEX IF NOT EXISTS idx_water_logs_user_date ON water_logs(user_id, date);
CREATE INDEX IF NOT EXISTS idx_nutrition_logs_user ON nutrition_logs(user_id, logged_at);
CREATE INDEX IF NOT EXISTS idx_workout_sessions_user ON workout_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_forum_topics_category ON forum_topics(category_id);
CREATE INDEX IF NOT EXISTS idx_forum_posts_topic ON forum_posts(topic_id);
CREATE INDEX IF NOT EXISTS idx_social_posts_user ON social_posts(user_id);
CREATE INDEX IF NOT EXISTS idx_follows_follower ON follows(follower_id);
CREATE INDEX IF NOT EXISTS idx_follows_following ON follows(following_id);
CREATE INDEX IF NOT EXISTS idx_health_data_user ON health_data(user_id, data_type);
CREATE INDEX IF NOT EXISTS idx_sleep_data_user ON sleep_data(user_id, date);
CREATE INDEX IF NOT EXISTS idx_videos_creator ON videos(creator_id);
CREATE INDEX IF NOT EXISTS idx_progress_logs_user ON progress_logs(user_id, log_type);

-- ============================================================
-- 14. CONTENT MODERATION & SAFETY
-- Columns and tables needed for NSFW detection, bans, and reporting
-- ============================================================

-- Add moderation columns to profiles
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS is_banned BOOLEAN DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS ban_reason TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS ban_expires_at TIMESTAMPTZ;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS content_violation_count INTEGER DEFAULT 0;

-- Content violations log
CREATE TABLE IF NOT EXISTS content_violations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    violation_type VARCHAR(100) NOT NULL, -- nsfw_profile_photo, inappropriate_message, etc.
    details TEXT,
    action_taken VARCHAR(50), -- warning, temp_ban, permanent_ban
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE content_violations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Only admins can view content violations"
ON content_violations FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'
    )
    OR auth.uid() = user_id
);
CREATE POLICY "System can insert violations"
ON content_violations FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Content reports (user-to-user reporting)
CREATE TABLE IF NOT EXISTS content_reports (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    reported_by UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    reported_user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    content_type VARCHAR(50) NOT NULL, -- profile_photo, message, forum_post, comment
    content_id TEXT, -- ID of the reported content
    reason TEXT NOT NULL,
    status VARCHAR(30) DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'resolved', 'dismissed')),
    reviewed_by UUID REFERENCES profiles(id),
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE content_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can report content"
ON content_reports FOR INSERT
WITH CHECK (auth.uid() = reported_by);
CREATE POLICY "Users can view own reports"
ON content_reports FOR SELECT
USING (auth.uid() = reported_by OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- Indexes for moderation tables
CREATE INDEX IF NOT EXISTS idx_content_violations_user ON content_violations(user_id);
CREATE INDEX IF NOT EXISTS idx_content_reports_status ON content_reports(status);
CREATE INDEX IF NOT EXISTS idx_content_reports_reported_user ON content_reports(reported_user_id);
CREATE INDEX IF NOT EXISTS idx_profiles_is_banned ON profiles(is_banned) WHERE is_banned = true;
